### ISSUE TITLE
LibreOffice in tabbed interface with menubar turned off crashes when Alt key is pressed

### ISSUE THREAD

**Issue by markochk** [flathub/org.libreoffice.LibreOffice#173]
Tested with Writer, Draw and Impress - all of them crash.

Steps to reproduce:
1. Set UI to Tabbed
2. Go to View tab > turn off menubar
3. Press and release `Alt` key. Only press the `Alt` key; ``Alt + ` ``, `Alt + Tab`  work fine.
4. LibreOffice crashes and opens Document Recovery dialog

LibreOffice info:
```
Version: 7.2.4.1 / LibreOffice Community
Build ID: 27d75539669ac387bb498e35313b970b7fe9c4f9
CPU threads: 8; OS: Linux 5.15; UI render: default; VCL: gtk3
Locale: en-US (en_US.UTF-8); UI: en-US
Flatpak
Calc: threaded
```
uname -a: `Linux fedora-marko 5.15.6-200.fc35.x86_64 #1 SMP Wed Dec 1 13:41:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
OS: Fedora 35, GNOME 41.2, Wayland

On non-flatpak LibreOffice installed from Fedora repos this crash doesn't occur. Non-flatpak version tested:
```
Version: 7.2.4.1
Build ID: 20(Build:1)
CPU threads: 8; OS: Linux 5.15; UI render: default; VCL: gtk3
Locale: en-US (en_US.UTF-8); UI: en-US
Calc: threaded
```

**Comment by stbergmann** [comment]
The flatpak scenario crashes with
```
Thread 1 "soffice.bin" received signal SIGSEGV, Segmentation fault.
0x00007ffff0813cca in g_type_check_instance_cast () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
(gdb) bt
#0  0x00007ffff0813cca in g_type_check_instance_cast () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007fffeeb05bef in GtkSalFrame::HandleMenubarMnemonic(unsigned int, unsigned int) (nKeyval=65513, eState=<optimized out>, this=<optimized out>, this=<optimized out>) at /app/lib/debug/source/libreoffice/vcl/unx/gtk3/gtkframe.cxx:3763
#2  0x00007fffeeb0c951 in GtkSalFrame::HandleMenubarMnemonic(unsigned int, unsigned int) (nKeyval=<optimized out>, eState=<optimized out>, this=0x5555568b04b0) at /app/lib/debug/source/libreoffice/vcl/unx/gtk3/gtkframe.cxx:3759
#3  GtkSalFrame::signalKey(_GtkWidget*, _GdkEventKey*, void*) (pWidget=0x5555565f3220, pEvent=0x55555bf0e5a0, frame=0x5555568b04b0) at /app/lib/debug/source/libreoffice/vcl/unx/gtk3/gtkframe.cxx:3791
#4  0x00007fffee588441 in _gtk_marshal_BOOLEAN__BOXED () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#5  0x00007ffff07f1349 in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff0804a7f in signal_emit_unlocked_R () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff080b1bb in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff080ba43 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007fffee52dea4 in gtk_widget_event_internal.part () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007fffee3d3167 in propagate_event () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007fffee3d4cac in gtk_main_do_event () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007fffee0a1192 in _gdk_event_emit () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#13 0x00007fffee0fd6af in gdk_event_source_dispatch () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#14 0x00007ffff06fd2a1 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff06fd548 in g_main_context_iterate.constprop () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff06fd614 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007fffeea8bce4 in GtkSalData::Yield(bool, bool) (this=0x55555567d030, bWait=<optimized out>, bHandleAllCurrentEvents=<optimized out>) at /app/lib/debug/source/libreoffice/vcl/unx/gtk3/gtkdata.cxx:391
#18 0x00007ffff4532edc in ImplYield(bool, bool) (i_bWait=i_bWait@entry=true, i_bAllEvents=i_bAllEvents@entry=false) at /app/lib/debug/source/libreoffice/vcl/source/app/svapp.cxx:465
#19 0x00007ffff4533800 in Application::Yield() () at /app/lib/debug/source/libreoffice/vcl/source/app/svapp.cxx:532
#20 0x00007ffff45357ed in Application::Execute() () at /app/lib/debug/source/libreoffice/vcl/source/app/svapp.cxx:444
#21 0x00007ffff7e9da0b in desktop::Desktop::Main() (this=0x7fffffffdb10) at /app/lib/debug/source/libreoffice/desktop/source/app/app.cxx:1587
#22 0x00007ffff453e6f1 in ImplSVMain() () at /app/lib/debug/source/libreoffice/vcl/source/app/svmain.cxx:199
#23 0x00007ffff7ec558c in soffice_main() () at /app/lib/debug/source/libreoffice/desktop/source/app/sofficemain.cxx:98
#24 0x00005555555550b8 in sal_main () at /app/lib/debug/source/libreoffice/desktop/source/app/main.c:49
#25 main (argc=<optimized out>, argv=<optimized out>) at /app/lib/debug/source/libreoffice/desktop/source/app/main.c:47
#26 0x00007ffff7ca4b90 in __libc_start_main () at /usr/lib/x86_64-linux-gnu/libc.so.6
#27 0x00005555555550fe in _start () at /buildstream/freedesktop-sdk/bootstrap/glibc.bst/csu/../sysdeps/x86_64/start.S:120
```
The non-flatpak scenario, though not crashing, prints to stderr
```
(soffice:205476): GLib-GObject-WARNING **: 14:56:35.716: invalid unclassed pointer in cast to 'GtkContainer'

(soffice:205476): Gtk-CRITICAL **: 14:56:35.716: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed
```
@caolanm: Any idea?

**Comment by caolanm** [comment]
I can reproduce locally. https://gerrit.libreoffice.org/c/core/+/126866 should be enough

**Comment by markochk** [comment]
Sorry for not updating earlier; I just tested LibreOffice version 7.3.0.3 and the bug is gone, so I'm closing the issue. Thank you for fixing it!
